# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13nU3D2llK7ERy9RdO2r6KOaUj1MMsY6Z
"""

import torch
import torch.nn as nn
from transformers import DetrImageProcessor, DetrForObjectDetection, ViTModel, ViTImageProcessor
from PIL import Image

# ==============================
# 1. Multi-Task Fruit Estimator
# ==============================
class FruitEstimator(nn.Module):
    def __init__(self):
        super(FruitEstimator, self).__init__()
        self.vit = ViTModel.from_pretrained("google/vit-base-patch16-224")
        hidden_size = self.vit.config.hidden_size

        # Multi-head outputs
        self.freshness_head = nn.Linear(hidden_size, 2)   # Fresh / Rotten
        self.ripeness_head  = nn.Linear(hidden_size, 3)   # Unripe / Ripe / Overripe
        self.edible_head    = nn.Linear(hidden_size, 2)   # Eatable / Not Eatable

    def forward(self, pixel_values):
        outputs = self.vit(pixel_values=pixel_values)
        pooled = outputs.last_hidden_state[:, 0]  # CLS token
        return {
            "freshness": self.freshness_head(pooled),
            "ripeness": self.ripeness_head(pooled),
            "edible": self.edible_head(pooled)
        }

# Preprocessors
detector = DetrForObjectDetection.from_pretrained("facebook/detr-resnet-50")
processor_det = DetrImageProcessor.from_pretrained("facebook/detr-resnet-50")

fruit_estimator = FruitEstimator()
processor_vit = ViTImageProcessor.from_pretrained("google/vit-base-patch16-224")

# ==============================
# 2. Prediction Helper
# ==============================
def classify_fruit(image_crop):
    inputs = processor_vit(image_crop, return_tensors="pt")
    with torch.no_grad():
        outputs = fruit_estimator(inputs["pixel_values"])

    results = {}
    tasks = {
        "Freshness": (["Rotten", "Fresh"], outputs["freshness"]),
        "Ripeness": (["Unripe", "Ripe", "Overripe"], outputs["ripeness"]),
        "Edibility": (["Not Eatable", "Eatable"], outputs["edible"])
    }

    for task, (labels, logits) in tasks.items():
        probs = torch.softmax(logits, dim=-1).squeeze().tolist()
        best_idx = int(torch.argmax(torch.tensor(probs)))
        results[task] = (labels[best_idx], round(probs[best_idx]*100, 2))
    return results

# ==============================
# 3. Full Pipeline: Detection + Classification
# ==============================
def detect_and_classify(image_path):
    image = Image.open(image_path).convert("RGB")
    inputs = processor_det(images=image, return_tensors="pt")
    outputs = detector(**inputs)

    target_sizes = torch.tensor([image.size[::-1]])
    results = processor_det.post_process_object_detection(
        outputs, target_sizes=target_sizes, threshold=0.7
    )[0]

    fruit_count = len(results["scores"])
    print(f"\nDetected Fruits: {fruit_count}\n")

    for i, (box, score, label) in enumerate(zip(results["boxes"], results["scores"], results["labels"])):
        xmin, ymin, xmax, ymax = box.int().tolist()
        crop = image.crop((xmin, ymin, xmax, ymax))

        print(f"Fruit {i+1}:")
        pred = classify_fruit(crop)
        for k, (v, p) in pred.items():
            print(f" - {k}: {v} ({p}%)")
        print("----")

# ==============================
# 4. Run Example
# ==============================
if __name__ == "__main__":
    # Replace with your image path
    detect_and_classify("banana.jpeg")